---
name: markdown-lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: markdown-lint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  markdown-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3b9b8c884f6b4bb4d5be2779c26374abadae0871
      - uses: articulate/actions-markdownlint@v1
