---
name: markdown-lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: markdown-lint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  markdown-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08
      - uses: articulate/actions-markdownlint@v1
